version: "3.6"
services:
        portainer:
                image: portainer/portainer-ce:latest
                container_name: portainer
                restart: always
                command: -H unix:///var/run/docker.sock
                ports:
                        - "9001:9000"
                volumes:
                        - /var/run/docker.sock:/var/run/docker.sock
                        - ${USERDIR}/docker/portainer/data:/data
                        - ${USERDIR}/docker/shared:/shared
                environment:
                        - TZ=${TZ}

        watchtower:
                image: containrrr/watchtower:latest
                container_name: watchtower
                restart: unless-stopped
                volumes:
                        - /var/run/docker.sock:/var/run/docker.sock
                        - ${USERDIR}/docker/shared:/shared
                environment:
                        - TZ=${TZ}
        plexms:
                container_name: plexms
                restart: always
                image: plexinc/pms-docker:public
                devices:
                        - /dev/dri:/dev/dri
                volumes:
                        - ${USERDIR}/docker/plexms:/config
                        - ${USERDIR}/Downloads/plex_tmp:/transcode
                        - /media/plexms-library/movies:/data/movies
                        - /media/plexms-library/tv:/data/tv
                        - /media/media:/media
                        - ${USERDIR}/docker/shared:/shared
                ports:
                        - "32400:32400/tcp"
                        - "3005:3005/tcp"
                        - "8324:8324/tcp"
                        - "32469:32469/tcp"
                        - "1900:1900/udp"
                        - "32410:32410/udp"
                        - "32412:32412/udp"
                        - "32413:32413/udp"
                        - "32414:32414/udp"
                environment:
                        - TZ=${TZ}
                        - HOSTNAME="Nut Server Plex"
                        - PLEX_CLAIM="claim-rW515H7xfh7etBnXQj29"
                        - PLEX_UID=${PUID}
                        - PLEX_GID=${PGID}
                        - ADVERTISE_IP="http://192.168.1.230:32400/"
                        - VERSION=docker
        sabnzbd:
                image: "linuxserver/sabnzbd:latest"
                container_name: "sabnzbd"
                volumes:
                        - ${USERDIR}/docker/sabnzbd:/config
                        - ${USERDIR}/Downloads/completed:/downloads
                        - ${USERDIR}/Downloads/incomplete:/incomplete-downloads
                        - ${USERDIR}/docker/shared:/shared
                        - /media/plexms-library:/plexms-library
                ports:
                        - "8080:8080"
                restart: unless-stopped
                environment:
                        - PUID=${PUID}
                        - PGID=${PGID}
                        - TZ=${TZ}
        radarr:
                image: "linuxserver/radarr:latest"
                container_name: "radarr"
                volumes:
                        - ${USERDIR}/docker/radarr:/config
                        - ${USERDIR}/Downloads/completed:/downloads
                        - /media/plexms-library/movies:/plexms-library/movies
                        - "/etc/localtime:/etc/localtime:ro"
                        - ${USERDIR}/docker/shared:/shared
                ports:
                        - "7878:7878"
                restart: unless-stopped
                environment:
                        - PUID=${PUID}
                        - PGID=${PGID}
                        - TZ=${TZ}
        sonarr:
                image: "linuxserver/sonarr:latest"
                container_name: "sonarr"
                volumes:
                        - ${USERDIR}/docker/sonarr:/config
                        - ${USERDIR}/Downloads/completed:/downloads
                        - /media/plexms-library/tv:/tv
                        - "/etc/localtime:/etc/localtime:ro"
                        - ${USERDIR}/docker/shared:/shared
                ports:
                        - "8989:8989"
                restart: unless-stopped
                environment:
                        - PUID=${PUID}
                        - PGID=${PGID}
                        - TZ=${TZ}
        hydra:
                image: "linuxserver/hydra:latest"
                container_name: "hydra"
                volumes:
                        - ${USERDIR}/docker/hydra:/config
                        - ${USERDIR}/Downloads:/downloads
                        - ${USERDIR}/docker/shared:/shared
                ports:
                        - "5075:5075"
                restart: unless-stopped
                environment:
                        - PUID=${PUID}
                        - PGID=${PGID}
                        - TZ=${TZ}
        duplicati:
                image: "linuxserver/duplicati:latest"
                container_name: "duplicati"
                ports:
                        - "8200:8200"
                restart: unless-stopped
                environment:
                        - PUID=${PUID}
                        - PGID=${PGID}
                        - TZ=${TZ}
                volumes:
                        - ${USERDIR}/docker/duplicati:/config
                        - ${USERDIR}/docker/duplicati:/backups
                        - /media:/source
        minecraft:
                image: "itzg/minecraft-bedrock-server:latest"
                container_name: "minecraft"
                ports:
                        - "19132:19132/udp"
                restart: unless-stopped
                environment:
                        - TZ=${TZ}
                        - VERSION=LATEST
                        - EULA=TRUE
                        - VERSION=1.16.5
                        - SERVER_NAME=NutMine
                        - GAMEMODE=survival
                        - DIFFICULTY=easy

                volumes:
                        - ${USERDIR}/docker/minecraft:/data
        ddns-updater:
                image: qmcgaw/ddns-updater
                container_name: ddns-updater
                network_mode: bridge
                ports:
                - 8000:8000/tcp
                volumes:
                - ${USERDIR}/docker/ddns/data:/updater/data
                environment:
                - CONFIG=
                - PERIOD=5m
                - UPDATE_COOLDOWN_PERIOD=5m
                - PUBLICIP_FETCHERS=all
                - PUBLICIP_HTTP_PROVIDERS=all
                - PUBLICIPV4_HTTP_PROVIDERS=all
                - PUBLICIPV6_HTTP_PROVIDERS=all
                - PUBLICIP_DNS_PROVIDERS=all
                - PUBLICIP_DNS_TIMEOUT=3s
                - HTTP_TIMEOUT=10s

                # Web UI
                - LISTENING_ADDRESS=:8000
                - ROOT_URL=/

                # Backup
                - BACKUP_PERIOD=0 # 0 to disable
                - BACKUP_DIRECTORY=/updater/data

                # Other
                - LOG_LEVEL=info
                - LOG_CALLER=hidden
                - SHOUTRRR_ADDRESSES=
                restart: always
