version: "3.6"
services:
        portainer:
                image: portainer/portainer
                container_name: portainer
                restart: always
                command: -H unix:///var/run/docker.sock
                ports:
                        - "9001:9000"
                volumes:
                        - /var/run/docker.sock:/var/run/docker.sock
                        - ${USERDIR}/docker/portainer/data:/data
                        - ${USERDIR}/docker/shared:/shared
                environment:
                        - TZ=${TZ}
        plexms:
                container_name: plexms
                restart: always
                image: plexinc/pms-docker
                volumes:
                        - ${USERDIR}/docker/plexms:/config
                        - ${USERDIR}/Downloads/plex_tmp:/transcode
                        - /media/media:/media
                        - ${USERDIR}/docker/shared:/shared
                ports:
                        - "32400:32400/tcp"
                        - "3005:3005/tcp"
                        - "8324:8324/tcp"
                        - "32469:32469/tcp"
                        - "1900:1900/udp"
                        - "32410:32410/udp"
                        - "32412:32412/udp"
                        - "32413:32413/udp"
                        - "32414:32414/udp"
                environment:
                        - TZ=${TZ}
                        - HOSTNAME="Nut Server Plex"
                        - PLEX_CLAIM="claim-bY3QbVsM4VSRw8psdNTR"
                        - PLEX_UID=${PUID}
                        - PLEX_GID=${PGID}
                        - ADVERTISE_IP="http://192.168.1.230:32400/"
